"""Generate client schema types and a reviewable OpenAPI snapshot without extra tooling."""
import argparse
import json
from pathlib import Path
import re
import sys
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from main import app

root=Path(__file__).resolve().parents[2]
schema=app.openapi()

def name(raw): return re.sub(r'[^a-zA-Z0-9_]','_',raw)

def ts(s):
    if '$ref' in s: return name(s['$ref'].rsplit('/',1)[-1])
    if 'const' in s:return json.dumps(s['const'])
    if 'enum' in s:return ' | '.join(json.dumps(v) for v in s['enum'])
    if 'anyOf' in s or 'oneOf' in s:return ' | '.join(ts(v) for v in s.get('anyOf',s.get('oneOf')))
    if 'allOf' in s:return ' & '.join(ts(v) for v in s['allOf'])
    typ=s.get('type')
    if typ=='array':return '('+ts(s.get('items',{}))+')[]'
    if typ=='object' or 'properties' in s:
        props=s.get('properties',{})
        parts=[json.dumps(k)+('' if k in s.get('required',[]) else '?')+': '+ts(v) for k,v in props.items()]
        extra=s.get('additionalProperties')
        if extra:parts.append('[key: string]: '+(ts(extra) if isinstance(extra,dict) else 'unknown'))
        return '{ '+'; '.join(parts)+' }' if parts else 'Record<string, unknown>'
    return {'string':'string','number':'number','integer':'number','boolean':'boolean','null':'null'}.get(typ,'unknown')

outputs={root/'backend/openapi.json':json.dumps(schema,indent=2,ensure_ascii=False)+'\n',root/'src/api/generated.ts':'// Generated by backend/scripts/generate_contracts.py. Do not edit.\n\n'+'\n\n'.join('export type '+name(k)+' = '+ts(v)+';' for k,v in sorted(schema['components']['schemas'].items()))+'\n'}
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
for path,content in outputs.items():
    if args.check:
        if not path.exists() or path.read_text()!=content:raise SystemExit(f'Contract drift: {path.relative_to(root)}')
    else:path.write_text(content)
print('Contracts checked' if args.check else 'Contracts generated')
