// Generated by backend/scripts/generate_contracts.py. Do not edit.

export type Activation = { "id": string; "parameter_version": string };

export type Approval = { "request_id": string; "candidates": (CandidateDecision)[]; "expected_draft_revision"?: number | null };

export type ApprovalRequest = { "operation_id"?: string | null; "content_revision": number };

export type Approve = { "code": string; "operation_id"?: string | null };

export type AssessmentRequest = { "item_id": string; "answer": string; "attempt_id": string; "content_revision": number; "language"?: string; "assisted"?: boolean };

export type AssessmentResult = { "id": string; "assessment_id": string; "item_id": string; "mode"?: "recall" | "tutor"; "content_revision": number; "rubric_revision"?: number | null; "decision"?: "correct" | "partial" | "incorrect" | "uncertain"; "feedback": string; "reason": string; "coverage"?: number | null; "confidence"?: number | null; "experimental"?: boolean; "assisted"?: boolean; "concept_results"?: (ConceptResult)[]; "versions": { [key: string]: string | null } };

export type BlockCorrection = { "operation_id": string; "expected_revision": number; "text": string };

export type Body_extract_pdf_extract_pdf_post = { "file": string };

export type Body_upload_ingestion_jobs_post = { "file": string; "request_id": string; "instructions"?: string; "crop"?: string | null; "extraction_mode"?: string };

export type Bootstrap = { "bootstrap_secret": string; "device_name": string; "operation_id"?: string | null };

export type CandidateDecision = { "id": string; "accept": boolean; "reviewed"?: boolean; "word": string; "definition": string; "example_sentence"?: string; "mnemonic"?: string | null; "etymology"?: string | null; "tag_ids"?: (string)[]; "reference_language"?: "en" | "hi" | "hi-Latn" };

export type CardState = { "card_id": number; "state": number; "step"?: number | null; "stability"?: number | null; "difficulty"?: number | null; "due": string; "last_review"?: string | null };

export type ChatMessage = { "role": "user" | "assistant"; "content": string };

export type Concept = { "id": string; "text": string; "weight"?: number; "required"?: boolean; "accepted_alternatives"?: (string)[]; "qualifiers"?: (string)[]; "misconceptions"?: (string)[] };

export type ConceptResult = { "concept_id": string; "text": string; "weight": number; "required": boolean; "alignment": number; "entailment": number; "neutrality": number; "contradiction": number; "support": number; "evidence_span": string; "contradiction_span"?: string | null; "qualifier_support"?: ({ [key: string]: unknown })[]; "misconception_support"?: ({ [key: string]: unknown })[] };

export type Correction = { "id": string; "rating": 1 | 3 | null; "reason": string };

export type CreateTagRequest = { "id": string; "name": string };

export type CreateWordRequest = { "id": string; "word": string; "definition": string; "example_sentence": string; "mnemonic"?: string | null; "source_type"?: string | null; "created_at": number; "updated_at": number; "sense_id"?: string | null; "etymology"?: string | null };

export type DraftSave = { "request_id": string; "candidates": (CandidateDecision)[]; "expected_draft_revision"?: number | null; "operation_id": string; "expected_revision": number };

export type ExtractedWord = { "word": string; "definition": string; "example_sentence": string; "mnemonic"?: string | null };

export type ExtractionRequest = { "input_type": "image" | "text" | "word"; "content": string; "mime_type"?: string | null; "instructions"?: string | null };

export type FitRequest = { "id": string; "mode": "recall" | "flashcard" };

export type GenerateStoryRequest = { "words": (WordItem)[]; "custom_prompt"?: string };

export type HTTPValidationError = { "detail"?: (ValidationError)[] };

export type JobMutation = { "operation_id": string; "expected_revision": number };

export type LegacyArchive = { "id": string; "data": { [key: string]: unknown } };

export type LlmCall = { "provider": string; "model": string; "task": string; "called_at": number };

export type LlmStatsResponse = { "period": "today" | "week" | "month" | "all"; "total_calls": number; "by_provider": (ProviderCount)[]; "calls": (LlmCall)[] };

export type MemoryState = { "learner_id"?: string; "item_id": string; "mode": "recall" | "flashcard"; "state_version": number; "progress_generation": number; "parameter_version": string; "updated_at": string; "card": CardState; "due": string; "retrievability"?: number | null };

export type MergeTagRequest = { "target_tag_id": string };

export type PromptRecord = { "id": string; "prompt_text": string; "default_text": string };

export type PromptUpdateRequest = { "prompt_text": string };

export type ProviderCount = { "provider": string; "model": string; "count": number };

export type ProvidersResponse = { "providers": (string)[] };

export type Reset = { "id": string; "expected_generation": number };

export type ReviewEventSummary = { "id": string; "item_id": string; "mode": "recall" | "flashcard"; "rating": number | null; "answered_at": string; "status": "acknowledged" | "practice"; "reason"?: string | null; "assessment_id"?: string | null; "experimental"?: boolean; "progress_generation": number; "device_id": string };

export type ReviewResult = { "id": string; "status": "acknowledged" | "practice"; "reason"?: string | null; "rating"?: number | null; "memory_state"?: MemoryState | null; "reconciled"?: boolean };

export type ReviewSubmission = { "id": string; "item_id": string; "mode": "recall" | "flashcard"; "answered_at": string; "device_sequence": number; "content_revision": number; "progress_generation": number; "expected_state_version"?: number | null; "settings_revision"?: number | null; "parameter_version"?: string | null; "rating"?: 1 | 3 | null; "assessment_id"?: string | null; "assisted"?: boolean; "revealed"?: boolean; "offline"?: boolean };

export type RubricInput = { "operation_id"?: string | null; "content_revision": number; "reference_language"?: "en" | "hi" | "hi-Latn"; "concepts": (Concept)[] };

export type RubricRecord = { "operation_id"?: string | null; "content_revision": number; "reference_language"?: "en" | "hi" | "hi-Latn"; "concepts": (Concept)[]; "id": string; "item_id": string; "revision": number; "status": "draft" | "approved" | "retired"; "created_at": number; "approved_at"?: number | null };

export type SavedStory = { "id": string; "tag_id"?: string | null; "prompt"?: string | null; "title": string; "content": string; "created_at": number };

export type Settings = { "learner_id"?: string; "desired_retention": number; "experimental_grading": boolean; "revision": number; "progress_generation": number };

export type SettingsUpdate = { "id"?: string | null; "desired_retention"?: number | null; "experimental_grading"?: boolean | null; "expected_revision": number };

export type Snapshot = { "version": number; "server_time": string; "words": (WordRecord)[]; "tags": (TagInfo)[]; "memory_states": (MemoryState)[]; "reviews": (ReviewEventSummary)[]; "settings": Settings; "rubrics": ({ [key: string]: unknown })[]; "parameter_versions": ({ [key: string]: unknown })[] };

export type Start = { "device_name": string; "operation_id"?: string | null };

export type StoryResponse = { "title": string; "content": string };

export type TagInfo = { "id": string; "name": string };

export type TagRecord = { "id": string; "name": string; "word_count"?: number };

export type TextUpload = { "request_id": string; "text": string; "instructions"?: string; "extraction_mode"?: "general_document" | "vocabulary_mcq" };

export type TutorChatRequest = { "item_id": string; "answer": string; "attempt_id": string; "content_revision": number; "language"?: string; "assisted"?: boolean; "history"?: (ChatMessage)[]; "is_retry"?: boolean };

export type TutorResponse = { "assessment": AssessmentResult; "response": string; "evaluation": "correct" | "partial" | "incorrect" | "uncertain"; "hint_provided"?: boolean; "audio_b64"?: string | null; "audio_error"?: string | null };

export type UpdateTagRequest = { "name": string };

export type UpdateWordRequest = { "word"?: string | null; "definition"?: string | null; "example_sentence"?: string | null; "mnemonic"?: string | null; "etymology"?: string | null; "expected_content_revision"?: number | null };

export type ValidationError = { "loc": (string | number)[]; "msg": string; "type": string; "input"?: unknown; "ctx"?: Record<string, unknown> };

export type WordItem = { "word": string; "definition": string };

export type WordRecord = { "id": string; "word": string; "definition": string; "example_sentence": string; "mnemonic"?: string | null; "source_type"?: string | null; "created_at": number; "updated_at": number; "deleted_at"?: number | null; "sense_id": string; "content_revision"?: number; "etymology"?: string | null; "tags"?: (TagInfo)[] };
